### ISSUE TITLE
RTE's feedback

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [rte-i/Antares_Simulator#13] opened 2022-03-08 05:20 UTC
_Edited with already tackled modifications_

Here is the feedback I got from RTE on the AdequacyFirstStep-initialization and link-constraints-management branches. Overall, it's mostly minor stuff. Please leave a reply to this if you are working on one of them so that we don't work on it twice.

1. ~~On [line 45 of src/solver/variable/economy/domesticUnsuppliedEnergy.h](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/solver/variable/economy/domesticUnsuppliedEnergy.h#L45), the "LOCAL UNSP. ENRG" should be changed to a **shorter name** to fit in the GUI. Florian simply suggested DENS or Local ENS.~~
2. ~~On [line 55 of src/solver/variable/economy/domesticUnsuppliedEnergy.h](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/solver/variable/economy/domesticUnsuppliedEnergy.h#L55), we should switch "Not Served" with "Unsupplied", to be **consistent** with Antares vocabulary. We should also switch "before exchange" to "without interconnections/links".~~
3. ~~**Build the AdequacyPatch namespace** inside of src/libs/antares/study/fwd.h,~~
    - ~~Put the [Mode enumeration](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/fwd.h#L122) and the [NTC enumeration](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/fwd.h#L136) inside the namespace.~~
    - ~~Change occurrences of the mode like [this](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/area/area.cpp#L56) and [this](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/area/area.h#L229) to use the AdequacyPatch namespace:`adequacyPatchMode(Data::AdequacyPatch::PhysicalAreaOutside),` and `Data::AdequacyPatch::Mode adequacyPatchMode;`~~
4. ~~In the NTC enumeration of the fwd.h file, the start and end should be switched to origin and extremity or from/to as that's more **consistent** with Antares vocabulary. (so [setStartEndToZero](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/fwd.h#L143) can become like setOrigineExtremityToZero)~~
5. ~~In [src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp#L437), the maximum bound we set on the ENS should also **consider previously set bounds**. Meaning that instead of using ValeursHorairesDENS directly, we should use min(Xmax, ValeursHorairesDENS).~~
6. ~~We should consider putting [this conversion](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/area/list.cpp#L339) and [that one](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/area/list.cpp#L1089) in separate methods if we might re-use them.~~ _Abandoned_
7. ~~In the UI, we want to be able to update the AdequacyPatchMode of multiple areas at once. [This condition](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/ui/simulator/windows/inspector/frame.cpp#L794) in src/ui/simulator/windows/inspector/frame.cpp prevents that. We should copy the behavior of the Unsupplied Energy pPGUnsupplied to fix this.~~
8. ~~Using SIM_RenseignementProblemeHebdo to prepare the problem for its second resolution seems to be ok. We should leave a TODO around in the future to check if we need to cut SIM_RenseignementProblemeHebdo and just pick out the part that we need.~~
9. ~~We need to merge the official develop branch inside our feature branch and solve the conflicts to get ready.~~

Some other stuff which is less important:

10. ~~We should consider using a smart pointer [for this](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/solver/simulation/sim_calcul_economique.cpp#L66). Something like:~~
```
struct AdequacyPatch {
bool firstStep = true;
// ...
};
std::unique_ptr<AdequacyPatch> adqPatch = nullptr;
```
So that we can write:
`if (problem.adqPatch && problem.adqPatch->firstStep)
// ...`

11. ~~We should consider using an enumeration [here](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/solver/simulation/sim_structure_probleme_economique.h#L482) to avoid conversion back and forth.~~
12. ~~We should consider having [this initialization](https://github.com/rte-i/Antares_Simulator/blob/4e0c1a940013e03ae9cd5c2b19fc7a9c5430fb59/src/libs/antares/study/area/area.cpp#L56) inside the class.~~ _Abandoned_

13. We should add Milos' test inside of Antares tests. To check with Florian on how to push on [the test repository](https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests).
14. ~~Group the Adequacy parameters in a sub category of the Optimization window.~~

I also got the confirmation that there is no need for an ADEQUACY_MAX, and that we shouldn't touch the transportation cost variable.

**Comment by rtei-pw** [comment] 2022-03-08 07:17
Hello I will start to look at the following:
3, 5, 7, 8

**Comment by Milos-RTEi** [comment] 2022-03-08 09:19
Hi, I'm ok with 1, 2 and 4. 
But 4 only after @rtei-pw finishes with 3, in order not to make conflicts.

**Comment by rtei-pw** [comment] 2022-03-08 09:20
Hello,
I pushed modif for 3, 5, 7, 8.
For 6, I do not see why we want to reuse those codes, so I will leave it as it is.

**Comment by Milos-RTEi** [comment] 2022-03-08 17:32
I took 11 also.

**Comment by Milos-RTEi** [comment] 2022-03-09 12:42
I proposed some additional changes for comment num.11 and tried to solve comment num.10 but gave up after some time. 
I'll pass num.12 also.

**Comment by Milos-RTEi** [comment] 2022-03-09 12:47
At Antares SharePoint I updated Test_study (1-Day) and Test_study (1-week) a little bit. I realized some improvements to the test models are necessary when I tested our final solution on Monday when we merged everything (prior to the rte comments implementation). And it actually worked! 
So if we don't mess it up with these 13 comments it will be ok.

**Comment by rtei-pw** [comment] 2022-03-11 05:34
For 9, I did a git merge develop on feature/adq-patch. there was no important conflict to solve. I still cannot reproduce the failed regression test 
https://github.com/rte-i/Antares_Simulator/pull/24

**Comment by hugo-antoine-rtei** [comment] 2022-03-14 23:26
Hello,
I think I helped with the pointer part, and I checked the behavior after N°9, everything seems to be working. That will conclude most of the changes requested, so if you guys are ok with it I propose to merge everything to the main branch, and then I'll send a PR towards RTE's side.

**Comment by rtei-pw** [comment] 2022-03-15 00:14
Cool, I merged all into feature/adq-patch.

**Comment by Milos-RTEi** [comment] 2022-03-15 08:28
All the results are same as before, when I first tested the solution. 
Actually there is a problem. All the results are the same when the adequacy patch is used (all NTC options works fine), but when the adequacy patch is set to false Antares provides NO results. Probably smart pointer branch created he issue.

**Closed as completed** 2022-03-22 23:09 UTC
Labels: enhancement
